adshayanB/ECE452

- .idea/inspectionProfiles/Project_Default.xml
- TimeLog.md
- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/farmeraid/App.kt
- app/src/main/java/com/example/farmeraid/MainActivity.kt
- app/src/main/java/com/example/farmeraid/data/InventoryRepository.kt
- app/src/main/java/com/example/farmeraid/data/QuotasRepository.kt
- app/src/main/java/com/example/farmeraid/data/module/RepositoryModule.kt
- app/src/main/java/com/example/farmeraid/home/HomeViewModel.kt
- app/src/main/java/com/example/farmeraid/home/model/HomeModel.kt
- app/src/main/java/com/example/farmeraid/home/views/HomeScreenView.kt
- app/src/main/java/com/example/farmeraid/ui/theme/Color.kt
- app/src/main/java/com/example/farmeraid/ui/theme/Theme.kt
- app/src/main/java/com/example/farmeraid/uicomponents/ButtonView.kt
- app/src/main/java/com/example/farmeraid/uicomponents/OutlinedButtonView.kt
- app/src/main/java/com/example/farmeraid/uicomponents/models/UiComponentModel.kt
- build.gradle
The PR includes the following:
- Button UI component for our primary button
- Button UI component for our outlined button
- Integrate Dagger Hilt for dependency injection. Required for use of Singleton Components (such as the Repositories set up in this PR)
- Scaffolded the full Home Mode MVVM structure with a Model, View, ViewModel, and usage with the Repository.
In the example below, the Test button switches the text between Tab.Quotas and Tab.Inventory. This will be used to later implement the tabs.
<video src="https://github.com/adshayanB/ECE452/assets/36520027/0fbbea79-36b1-498f-b601-af858b83e318"/>
> Scaffold Home Mode MVVM architecture, add Dagger Hilt, and create Button UI components

- .idea/.name
- app/build.gradle
- app/src/main/java/com/example/farmeraid/MainActivity.kt
- app/src/main/java/com/example/farmeraid/data/UserRepository.kt
- app/src/main/java/com/example/farmeraid/data/module/RepositoryModule.kt
- app/src/main/java/com/example/farmeraid/sign_in/SignInViewModel.kt
- app/src/main/java/com/example/farmeraid/sign_in/model/SignInModel.kt
- app/src/main/java/com/example/farmeraid/sign_in/views/SignInScreenView.kt
> Sign-in view

- .idea/.name
- .idea/misc.xml
- TimeLog.md
- app/src/main/java/com/example/farmeraid/data/UserRepository.kt
- app/src/main/java/com/example/farmeraid/navigation/NavRoute.kt
- app/src/main/java/com/example/farmeraid/navigation/RootNavigationHost.kt
- app/src/main/java/com/example/farmeraid/sign_in/SignInViewModel.kt
- app/src/main/java/com/example/farmeraid/sign_in/model/SignInModel.kt
- app/src/main/java/com/example/farmeraid/sign_in/views/SignInScreenView.kt
- app/src/main/java/com/example/farmeraid/sign_up/SignUpViewModel.kt
- app/src/main/java/com/example/farmeraid/sign_up/model/SignUpModel.kt
- app/src/main/java/com/example/farmeraid/sign_up/views/SignUpScreenView.kt
- app/src/main/java/com/example/farmeraid/uicomponents/BottomNavigationBar.kt
Added signup functionality with Firebase
https://github.com/adshayanB/ECE452/assets/41243143/8390b8b0-b95b-450c-b9f2-02041ee1abc4
Also added onclick between screens using navigation routes
https://github.com/adshayanB/ECE452/assets/41243143/dfe828ed-ee5d-4216-b713-175debf220f7
> Sign up functionality with Firebase

- .idea/gradle.xml
- .idea/misc.xml
- app/src/main/java/com/example/farmeraid/uicomponents/FloatingActionButtonView.kt
- app/src/main/java/com/example/farmeraid/uicomponents/models/UiComponentModel.kt
This is the Floating Action button that will be re-used for multiple screens to add a new list item or open the Mic.
Add New Item:
Mic:
Screen Position:
> feat: created floating button ui component for add and mic

- TimeLog.md
- app/src/main/java/com/example/farmeraid/sign_in/SignInViewModel.kt
- app/src/main/java/com/example/farmeraid/sign_in/model/SignInModel.kt
- app/src/main/java/com/example/farmeraid/sign_in/views/SignInScreenView.kt
- app/src/main/java/com/example/farmeraid/sign_up/SignUpViewModel.kt
- app/src/main/java/com/example/farmeraid/sign_up/views/SignUpScreenView.kt
- app/src/main/java/com/example/farmeraid/ui/theme/Theme.kt
> Polish up authentication UI and ensure that text fields are controlled solely by the viewmodel

- .idea/.name
- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/farmeraid/MainActivity.kt
- app/src/main/java/com/example/farmeraid/data/InventoryRepository.kt
- app/src/main/java/com/example/farmeraid/data/model/InventoryModel.kt
- app/src/main/java/com/example/farmeraid/farm/FarmViewModel.kt
- app/src/main/java/com/example/farmeraid/farm/model/FarmModel.kt
- app/src/main/java/com/example/farmeraid/farm/views/FarmScreenView.kt
- app/src/main/java/com/example/farmeraid/home/HomeViewModel.kt
- app/src/main/java/com/example/farmeraid/home/model/HomeModel.kt
- app/src/main/java/com/example/farmeraid/home/views/HomeScreenView.kt
- app/src/main/java/com/example/farmeraid/navigation/RootNavigationHost.kt
- app/src/main/java/com/example/farmeraid/speech_recognition/KontinuousSpeechRecognizer.kt
- app/src/main/java/com/example/farmeraid/speech_recognition/SpeechRecognizer.kt
- app/src/main/java/com/example/farmeraid/speech_recognition/module/SpeechRecognitionModule.kt
- app/src/main/java/com/example/farmeraid/uicomponents/IncrementListItem.kt
- app/src/main/java/com/example/farmeraid/uicomponents/QuantityPickerView.kt
- app/src/main/java/com/example/farmeraid/uicomponents/models/UiComponentModel.kt
- build.gradle
- settings.gradle
Integrated voice feature end to end.
Completed the frontend UI and connection to repository
> Integrated voice feature

- .idea/codeStyles/Project.xml
- .idea/codeStyles/codeStyleConfig.xml
- app/src/main/java/com/example/farmeraid/data/TransactionRepository.kt
- app/src/main/java/com/example/farmeraid/farm/FarmViewModel.kt
- app/src/main/java/com/example/farmeraid/farm/views/FarmScreenView.kt
- app/src/main/java/com/example/farmeraid/navigation/AppNavigator.kt
- app/src/main/java/com/example/farmeraid/navigation/NavRoute.kt
- app/src/main/java/com/example/farmeraid/navigation/RootNavigationHost.kt
- app/src/main/java/com/example/farmeraid/snackbar/SnackbarDelegate.kt
- app/src/main/java/com/example/farmeraid/transactions/TransactionsViewModel.kt
- app/src/main/java/com/example/farmeraid/transactions/model/TransactionsModel.kt
- app/src/main/java/com/example/farmeraid/transactions/views/TransactionsView.kt
This is the transaction screen, when navigating from Farm Mode:
Originally the branch was created to work on Farm Mode page, but afterwards, as the team required, work on transaction page was done instead. Hence, the branch was originally named FarmModeCards, but work on the transaction page was done.
Another side note to add, as there were ssh key issues on my laptop, there is a duplicate user, sdharask, which is still me, but is the user account attached to the ssh key linked to my Waterloo email. This was unintended, and I did want to work from my regular GitHub account, SoumilDharaskar. I will try to fix this moving forward, but just wanted to inform that sdharask is myself, pushing from my laptop.
> Farm Mode View

- .idea/deploymentTargetDropDown.xml
- TimeLog.md
- app/build.gradle
- app/src/main/java/com/example/farmeraid/data/MarketRepository.kt
- app/src/main/java/com/example/farmeraid/data/QuotasRepository.kt
- app/src/main/java/com/example/farmeraid/data/model/MarketModel.kt
- app/src/main/java/com/example/farmeraid/data/module/RepositoryModule.kt
- app/src/main/java/com/example/farmeraid/home/HomeViewModel.kt
- app/src/main/java/com/example/farmeraid/home/add_edit_quota/AddEditQuotaViewModel.kt
- app/src/main/java/com/example/farmeraid/home/add_edit_quota/model/AddEditQuotaModel.kt
- app/src/main/java/com/example/farmeraid/home/add_edit_quota/views/AddEditQuotaScreenView.kt
- app/src/main/java/com/example/farmeraid/home/views/QuotaItem.kt
- app/src/main/java/com/example/farmeraid/navigation/AppNavigator.kt
- app/src/main/java/com/example/farmeraid/navigation/NavRoute.kt
- app/src/main/java/com/example/farmeraid/navigation/RootNavigationHost.kt
- app/src/main/java/com/example/farmeraid/uicomponents/QuantityPickerView.kt
- app/src/main/java/com/example/farmeraid/uicomponents/SearchableExpandedDropdownMenuView.kt
- app/src/main/java/com/example/farmeraid/uicomponents/models/UiComponentModel.kt
<video src="https://github.com/adshayanB/ECE452/assets/36520027/418653b7-1a85-44cf-9f7f-dfffd0f8a8a6"/>
> Create add and edit quotas page

- app/src/main/java/com/example/farmeraid/home/add_edit_quota/AddEditQuotaViewModel.kt
- app/src/main/java/com/example/farmeraid/home/add_edit_quota/views/AddEditQuotaScreenView.kt
Fix weird padding on scroll
Before:
After:
> Polish create add quota page

- .idea/.name
- TimeLog.md
- app/src/main/java/com/example/farmeraid/data/QuotasRepository.kt
- app/src/main/java/com/example/farmeraid/home/add_edit_quota/views/AddEditQuotaScreenView.kt
- app/src/main/java/com/example/farmeraid/home/model/HomeModel.kt
- app/src/main/java/com/example/farmeraid/home/views/HomeScreenView.kt
- app/src/main/java/com/example/farmeraid/home/views/QuotaItem.kt
- app/src/main/java/com/example/farmeraid/uicomponents/ProgressBarView.kt
- app/src/main/java/com/example/farmeraid/uicomponents/models/UiComponentModel.kt
Improved the look of the progress bar, and made it a custom ui component so that is more modular and can be used in other pages later such as the specific quota page and the market page.
<video src="https://github.com/adshayanB/ECE452/assets/36520027/049f2eb5-63bb-4c2b-bd38-4657a649b66e"/>
> Improved progress bar and made it more modular

- .idea/.name
- firebase_database_schema.py
This CR contains a script that seeds the firebase collection using the proposed database schema. 
This code is written in python for simplicity and quick modifications of table data when needed for development purposes. It is merely a tool to help support other developers when they want to test their features. 
The proposed database design will look like the following: 
For more information see the database design document, in our readme.
> Developed Script to design and seed initial firebase database 

- app/src/main/java/com/example/farmeraid/data/InventoryRepository.kt
- app/src/main/java/com/example/farmeraid/data/UserRepository.kt
- app/src/main/java/com/example/farmeraid/data/model/UserModel.kt
Refactored the current inventory feature to pull follow our new db schema
> Refactored to support the new db schema

- app/src/main/java/com/example/farmeraid/data/FarmRepository.kt
- app/src/main/java/com/example/farmeraid/data/model/FarmModel.kt
- app/src/main/java/com/example/farmeraid/data/module/RepositoryModule.kt
Created the farm repository which is currently blocking farm creation and user farm join pages.
Allows users to create a farm
Also allows users to join farms with a given code
@adshayanB will need to add a field `code` to the farm collection so we can have join functionality
> farm repository

- TimeLog.md
- app/src/main/java/com/example/farmeraid/data/MarketRepository.kt
- app/src/main/java/com/example/farmeraid/data/QuotasRepository.kt
- app/src/main/java/com/example/farmeraid/data/model/MarketModel.kt
- app/src/main/java/com/example/farmeraid/home/add_edit_quota/AddEditQuotaViewModel.kt
- app/src/main/java/com/example/farmeraid/home/views/QuotaItem.kt
- Updated Quotas to support firebase implementation
- Quotas can be found using their marketid as it is only a 1:1 mapping
- Handles when a market does not have a quota
- Ability to view/update a quota harnessing firestore our backend db 
It is to note that markets are still hard coded, so hence the quotas for all the markets are currently the same. This will be changed through the next cr where each farm will have individual markets with individual quotas
Update flow (adding soumil to the quota):
> Refactored Quotas to support firebase implementation

- app/src/main/java/com/example/farmeraid/data/InventoryRepository.kt
- app/src/main/java/com/example/farmeraid/farm/FarmViewModel.kt
- app/src/main/java/com/example/farmeraid/home/HomeViewModel.kt
- app/src/main/java/com/example/farmeraid/home/add_edit_quota/AddEditQuotaViewModel.kt
This PR migrates the current inventory repository to fully use firestore. It also uses the new FAResponse and FAResponseWithData classes to send responses with errors if needed.
> Migrate inventory repository to firestore

- app/src/main/java/com/example/farmeraid/uicomponents/ProgressBarView.kt
- app/src/main/java/com/example/farmeraid/uicomponents/models/UiComponentModel.kt
You can customize the colour and expected progress number as part of the uistate.
> Add expected progress indicator to progress bar

- TimeLog.md
- app/src/main/java/com/example/farmeraid/create_farm/CreateFarmViewModel.kt
- app/src/main/java/com/example/farmeraid/create_farm/FarmCodeViewModel.kt
- app/src/main/java/com/example/farmeraid/create_farm/model/CreateFarmModel.kt
- app/src/main/java/com/example/farmeraid/create_farm/model/FarmCodeModel.kt
- app/src/main/java/com/example/farmeraid/create_farm/views/CreateFarmScreenView.kt
- app/src/main/java/com/example/farmeraid/create_farm/views/FarmCodeScreenView.kt
- app/src/main/java/com/example/farmeraid/data/FarmRepository.kt
- app/src/main/java/com/example/farmeraid/navigation/AppNavigator.kt
- app/src/main/java/com/example/farmeraid/navigation/NavRoute.kt
- app/src/main/java/com/example/farmeraid/navigation/RootNavigationHost.kt
- app/src/main/java/com/example/farmeraid/sign_in/SignInViewModel.kt
- app/src/main/java/com/example/farmeraid/uicomponents/BottomNavigationBar.kt
This PR does the following:
- Created MVVM for Create Farm and Farm Code screens
- Restricted navigation to Create Farm screen only if the user's FarmID is Empty or NULL
- Calls the Farm Repository function to create a new farm on Firestore
- Refactors Farm Repository to use the new Repository Response sealed class for try-catch
Demo:
https://github.com/adshayanB/ECE452/assets/36520183/85cb16f5-5572-47c9-8c46-579e80d9c4de
> Create Farm Screens and User Flow

- app/src/main/java/com/example/farmeraid/join_farm/JoinFarmViewModel.kt
- app/src/main/java/com/example/farmeraid/join_farm/model/JoinFarmModel.kt
- app/src/main/java/com/example/farmeraid/join_farm/views/JoinFarmScreenView.kt
- app/src/main/java/com/example/farmeraid/navigation/AppNavigator.kt
- app/src/main/java/com/example/farmeraid/navigation/NavRoute.kt
- app/src/main/java/com/example/farmeraid/navigation/RootNavigationHost.kt
- app/src/main/java/com/example/farmeraid/uicomponents/BottomNavigationBar.kt
This PR does the following:
- Created MVVM for Join Farm Screen
TODO:
- Restricted navigation to Join Farm screen only if the user's FarmID is Empty or NULL
- Assign the user ID to the Farm document in Firestore when user successfully enters Farm code
UI:
> Created the Join Farm screen

- .idea/deploymentTargetDropDown.xml
- app/src/main/java/com/example/farmeraid/create_farm/views/CreateFarmScreenView.kt
- app/src/main/java/com/example/farmeraid/farm_selection/FarmSelectionViewModel.kt
- app/src/main/java/com/example/farmeraid/farm_selection/model/FarmSelectionModel.kt
- app/src/main/java/com/example/farmeraid/farm_selection/views/FarmSelectionScreenView.kt
- app/src/main/java/com/example/farmeraid/join_farm/JoinFarmViewModel.kt
- app/src/main/java/com/example/farmeraid/navigation/AppNavigator.kt
- app/src/main/java/com/example/farmeraid/navigation/NavRoute.kt
- app/src/main/java/com/example/farmeraid/navigation/RootNavigationHost.kt
- app/src/main/java/com/example/farmeraid/sign_in/SignInViewModel.kt
- app/src/main/java/com/example/farmeraid/uicomponents/BottomNavigationBar.kt
This PR creates the basic Farm Selection page. 
Rebased with @PreyanshK  PR and connects flow together.
https://github.com/adshayanB/ECE452/assets/36520014/a03fed30-f5ac-447c-ac45-0fa4a5c6957d
> create farm selection page and nav routes

- TimeLog.md
- app/src/main/java/com/example/farmeraid/data/FarmRepository.kt
- app/src/main/java/com/example/farmeraid/data/MarketRepository.kt
- app/src/main/java/com/example/farmeraid/data/QuotasRepository.kt
- app/src/main/java/com/example/farmeraid/data/model/MarketModel.kt
- app/src/main/java/com/example/farmeraid/data/module/RepositoryModule.kt
- app/src/main/java/com/example/farmeraid/home/HomeViewModel.kt
- app/src/main/java/com/example/farmeraid/home/add_edit_quota/AddEditQuotaViewModel.kt
- app/src/main/java/com/example/farmeraid/home/view_quota/ViewQuotaViewModel.kt
Refactored Market Repo to pull data from firebase, updated Quotas and Farmer repos to provide the necessary data for firebase integration.
-Market View
-Quota View
> Refactored Farmer/Quotas/Market Schema to connect with firebase

- app/src/main/java/com/example/farmeraid/data/InventoryRepository.kt
- app/src/main/java/com/example/farmeraid/home/HomeViewModel.kt
- app/src/main/java/com/example/farmeraid/home/add_edit_produce/AddEditProduceViewModel.kt
- app/src/main/java/com/example/farmeraid/home/add_edit_produce/views/AddEditProduceScreenView.kt
- app/src/main/java/com/example/farmeraid/home/views/HomeScreenView.kt
- app/src/main/java/com/example/farmeraid/navigation/RootNavigationHost.kt
This PR adds the functionality to delete a produce.
<video src="https://github.com/adshayanB/ECE452/assets/36520027/e0f0c07c-b529-4938-9e8e-f7079da09991"/>
> Add/Edit produce page [2/2]

- app/src/main/java/com/example/farmeraid/data/InventoryRepository.kt
- app/src/main/java/com/example/farmeraid/home/HomeViewModel.kt
- app/src/main/java/com/example/farmeraid/home/add_edit_produce/AddEditProduceViewModel.kt
- app/src/main/java/com/example/farmeraid/home/add_edit_produce/model/AddEditProduceModel.kt
- app/src/main/java/com/example/farmeraid/home/add_edit_produce/views/AddEditProduceScreenView.kt
- app/src/main/java/com/example/farmeraid/home/views/HomeScreenView.kt
- app/src/main/java/com/example/farmeraid/home/views/ProduceItem.kt
- app/src/main/java/com/example/farmeraid/navigation/AppNavigator.kt
- app/src/main/java/com/example/farmeraid/navigation/NavRoute.kt
- app/src/main/java/com/example/farmeraid/navigation/RootNavigationHost.kt
This is the first of 2 PRs for the Add/Edit produce page. This has the full functionality of adding and editing produce. In the next PR, I will add delete produce support.
<video src="https://github.com/adshayanB/ECE452/assets/36520027/6b6a0242-f20f-4ba2-956a-58140939902a"/>
> Add/Edit produce page [1/2]

- .idea/deploymentTargetDropDown.xml
- app/build.gradle
- app/src/main/java/com/example/farmeraid/farm/FarmViewModel.kt
- app/src/main/java/com/example/farmeraid/speech_recognition/SpeechRecognizer.kt
Before  we were doing pluralization that was very simple with s/es. This wasn't handling complex situations with this PR we are now introducing a library that will handle that for us.
> Implement pluralizer 

- TimeLog.md
- app/src/main/java/com/example/farmeraid/home/views/HomeScreenView.kt
> Add empty inventory and empty quotas messages

- app/src/main/java/com/example/farmeraid/home/add_edit_quota/AddEditQuotaViewModel.kt
<video src="https://github.com/adshayanB/ECE452/assets/36520027/729ff797-279a-472e-8a1c-51d0fb4f6ce2"/>
> Navigate back on add/edit quota submit

- TimeLog.md
- app/src/main/java/com/example/farmeraid/data/CharityRepository.kt
- app/src/main/java/com/example/farmeraid/data/FarmRepository.kt
- app/src/main/java/com/example/farmeraid/data/model/CharityModel.kt
- app/src/main/java/com/example/farmeraid/data/model/FridgeModel.kt
- app/src/main/java/com/example/farmeraid/data/module/RepositoryModule.kt
- firebase_database_schema.py
CR creates a new repo for charity information based on the new schema
- Adds functionality to create and get a charity
- Create a get charity id function from farm repo
- Update seeding script to support new db schema changes 
The new Schema looks like the following:
Farm Object:
Charity Object:
> Fridge repo

- app/src/main/java/com/example/farmeraid/data/TransactionRepository.kt
- app/src/main/java/com/example/farmeraid/data/model/TransactionsModel.kt
- firebase_database_schema.py
This PR refactors the current transactions repository with the updated schema.
Also updates the python script to add new transactions.
> Refactor transactions repository with updated schema

- app/src/main/java/com/example/farmeraid/data/TransactionRepository.kt
- app/src/main/java/com/example/farmeraid/transactions/TransactionsViewModel.kt
This PR adds the ability to get the x most recent transactions based on the provided list of filters.
Demo:
<video src="https://github.com/adshayanB/ECE452/assets/36520027/a9901f01-7a7f-4100-a86c-2cf690802c2f"/>
> Expand get recent transactions function

- .idea/misc.xml
- TimeLog.md
- app/src/main/java/com/example/farmeraid/MainActivity.kt
- app/src/main/java/com/example/farmeraid/data/UserRepository.kt
- app/src/main/java/com/example/farmeraid/navigation/AppNavigator.kt
- app/src/main/java/com/example/farmeraid/navigation/NavRoute.kt
- app/src/main/java/com/example/farmeraid/navigation/RootNavigationHost.kt
- app/src/main/java/com/example/farmeraid/navigation/module/NavigatorModule.kt
- app/src/main/java/com/example/farmeraid/sign_in/LoadingViewModel.kt
- app/src/main/java/com/example/farmeraid/sign_in/SignInViewModel.kt
- app/src/main/java/com/example/farmeraid/sign_in/model/LoadingModel.kt
- app/src/main/java/com/example/farmeraid/sign_in/views/LoadingScreen.kt
- app/src/main/java/com/example/farmeraid/sign_out/SignOutViewModel.kt
- app/src/main/java/com/example/farmeraid/sign_out/model/SignOutModel.kt
- app/src/main/java/com/example/farmeraid/sign_out/views/SignOutScreenView.kt
- app/src/main/java/com/example/farmeraid/uicomponents/BottomNavigationBar.kt
This CR serves to enable users to log out as well as users who are logged in already to not log in again. 
A demo to indicate this feature is attached below: 
https://streamable.com/pu0usx
> Prevent login for already logged in user + Sign Out 

- .idea/misc.xml
- app/build.gradle
- app/src/main/java/com/example/farmeraid/data/MarketRepository.kt
- app/src/main/java/com/example/farmeraid/data/QuotasRepository.kt
- app/src/main/java/com/example/farmeraid/data/TransactionRepository.kt
- app/src/main/java/com/example/farmeraid/data/model/TransactionModel.kt
- app/src/main/java/com/example/farmeraid/data/module/RepositoryModule.kt
- app/src/main/java/com/example/farmeraid/home/add_edit_quota/AddEditQuotaViewModel.kt
- app/src/main/java/com/example/farmeraid/home/view_quota/views/ViewQuotaScreenView.kt
- app/src/main/java/com/example/farmeraid/home/views/QuotaItem.kt
- app/src/main/java/com/example/farmeraid/market/sell_produce/SellProduceViewModel.kt
This PR adds the functionality to check to see if our current date is within the week for quota sales, and if it isn't, it refetches the sale amounts for the new week. Added an "endOfWeek" field in the Quotas collection to support this functionality.
<video src="https://github.com/adshayanB/ECE452/assets/36520027/b325a5c2-2849-42bd-bd0a-b59410236b6f"/>
> Get updated weekly sale amounts for Quotas

- app/src/main/java/com/example/farmeraid/data/QuotasRepository.kt
This PR updates the quota sale amounts when you add a new quota and or update a quota.
> Update quota sale amounts on add/edit quota

- app/src/main/java/com/example/farmeraid/farm/FarmViewModel.kt
- app/src/main/java/com/example/farmeraid/farm/model/FarmModel.kt
- app/src/main/java/com/example/farmeraid/farm/views/FarmScreenView.kt
- app/src/main/java/com/example/farmeraid/transactions/TransactionsViewModel.kt
- app/src/main/java/com/example/farmeraid/transactions/model/TransactionsModel.kt
Added loading states for farm and transaction. 
@SoumilDharaskar as you are working on the transaction views could you update the ui using this state?
> added loading indicators and states

- app/src/main/java/com/example/farmeraid/data/TransactionRepository.kt
- app/src/main/java/com/example/farmeraid/data/model/TransactionModel.kt
- app/src/main/java/com/example/farmeraid/farm/FarmViewModel.kt
- app/src/main/java/com/example/farmeraid/market/sell_produce/SellProduceViewModel.kt
This PR adds the functionality to add new transactions from a Harvest or Sell. Once the Charity page is ready, I will add it the Donate transaction as well.
> Harvest and Sell Adds new transactions to the DB

- app/src/main/java/com/example/farmeraid/data/QuotasRepository.kt
- app/src/main/java/com/example/farmeraid/data/TransactionRepository.kt
- app/src/main/java/com/example/farmeraid/data/model/TransactionModel.kt
- app/src/main/java/com/example/farmeraid/farm/FarmViewModel.kt
- app/src/main/java/com/example/farmeraid/market/sell_produce/SellProduceViewModel.kt
Update the sales map in quotas when a sale is done in market
> Update sales for a market in quotas on sale

- app/src/main/java/com/example/farmeraid/farm/views/FarmScreenView.kt
Quick fix to update positioning of mic button on the farm page
> Fix mic button styling on Farm page
